steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'gcr.io/$PROJECT_ID/laravel-app:$COMMIT_SHA',
      '-t', 'gcr.io/$PROJECT_ID/laravel-app:latest',
      '.'
    ]

  # Push the image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/laravel-app:$COMMIT_SHA']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/laravel-app:latest']

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: [
      'run', 'deploy', 'laravel-app',
      '--image', 'gcr.io/$PROJECT_ID/laravel-app:$COMMIT_SHA',
      '--region', '${_REGION}',
      '--platform', 'managed',
      '--allow-unauthenticated',
      '--port', '8080',
      '--memory', '2Gi',
      '--cpu', '2',
      '--min-instances', '0',
      '--max-instances', '10',
      '--concurrency', '80',
      '--timeout', '300',
      '--set-env-vars', 'APP_ENV=production,APP_DEBUG=false,APP_KEY=${_APP_KEY}',
      '--add-cloudsql-instances', '${_DB_INSTANCE_CONNECTION_NAME}'
    ]

images:
  - 'gcr.io/$PROJECT_ID/laravel-app:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/laravel-app:latest'

substitutions:
  _REGION: 'us-central1'
  _DB_INSTANCE_CONNECTION_NAME: 'your-project:region:instance-name'
  _APP_KEY: 'your-generated-app-key'

options:
  machineType: 'E2_HIGHCPU_8'
  substitutionOption: 'ALLOW_LOOSE'