# Use the official PHP image with necessary extensions
FROM php:8.2-cli

# Install system dependencies
RUN apt-get update && apt-get install -y \  
    npm \
    nodejs
    
    
# Set working directory
WORKDIR /var/www

# Copy project files
COPY . .

# Install PHP depend
RUN npm install
# RUN npm install

# Set file permissions


EXPOSE 5173
CMD ["npm", "run", "dev"]
